[package]
name = "tomato"
version = "0.2.0"
edition = "2021"

[lib]
name = "tomato"
path = "src/lib.rs"

[dependencies]
thiserror = "2"
hnsw_rs = "0.3.3"
rand = "0.9"

reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
csv = "1"

[dev-dependencies]
proptest = "1"